export const REQUEST_PROFILES = `profiles/REQUEST_PROFILES`;
export const REQUEST_PROFILES_SUCCESS = `profiles/REQUEST_PROFILES_SUCCESS`;
export const REQUEST_PROFILES_ERROR = `profiles/REQUEST_PROFILES_ERROR`;
